require("mini.comment").setup()
require("mini.hipatterns").setup()
require("mini.fuzzy").setup()
require("mini.operators").setup()
require("mini.pairs").setup()
require("mini.starter").setup()
require("mini.surround").setup()
require("mini.trailspace").setup()

require("mini.completion").setup()
vim.keymap.set("i", "<Tab>", [[pumvisible() ? "\<C-n>" : "\<Tab>"]], { expr = true })
vim.keymap.set("i", "<S-Tab>", [[pumvisible() ? "\<C-p>" : "\<S-Tab>"]], { expr = true })
